---
- block:
  - name: Load overlay & br_netfilter on boot
    become: yes
    shell: | 
      cat <<EOF | tee /etc/modules-load.d/crio.conf
      overlay
      br_netfilter
      EOF && \
      modprobe overlay && \
      modprobe br_netfilter
  - name: Set sysctl params
    become: yes
    shell: |
      cat <<EOF | tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      EOF && \
      sysctl --system