---
- block:
  - name: Load kernel modules
    become: yes
    lineinfile:
      path: /etc/modules-load.d/crio.conf
      line: "{{ item }}"
      create: true
    loop:
      - overlay
      - br_netfilter

  - name: Load kernel modules
    become: yes
    modprobe:
      name: "{{ item }}"
    loop:
      - overlay
      - br_netfilter

  - name: Configure sysctl parameters
    become: yes
    copy:
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
      content: |
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
        net.bridge.bridge-nf-call-ip6tables = 1
  - name: Apply sysctl parameters
    become: yes
    command: sysctl --system