---
- block:
  - name: Check if ~/.kube/config already exists
    stat:
      path: /home/vagrant/.kube/config
    register: kube_config

  - name: Copy k8s config
    shell: |
      config_path="/vagrant/configs"
      whoami
      mkdir -p /home/vagrant/.kube
      sudo cp -i $config_path/config /home/vagrant/.kube/
      sudo chown 1000:1000 /home/vagrant/.kube/config
    when: not kube_config.stat.exists

  - name: Run join script
    shell: |
      config_path="/vagrant/configs"
      /bin/bash $config_path/join.sh -v
    become: true
    when: not kube_config.stat.exists

  - name: Label node
    shell: |
      NODENAME=$(hostname -s)
      kubectl label node $NODENAME node-role.kubernetes.io/worker=worker
    become: true
    become_user: vagrant
    when: not kube_config.stat.exists