---
- block:
  # Add CRI-O dependencies:
  - name: Import CRI-O repository keys
    become: yes
    apt_key:
      url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ kubernetes.version_short }}/{{ os }}/Release.key"
      state: present
      keyring: /etc/apt/trusted.gpg.d/libcontainers.gpg
    apt_key:
        url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os }}/Release.key"
        state: present
        keyring: /etc/apt/trusted.gpg.d/libcontainers.gpg


  - name: Add CRI-O version-specific repository
    become: yes
    apt_repository:
      repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ kubernetes.version_short }}/{{ os }}/ /"
      state: present
      filename: devel_kubic_libcontainers_stable_cri-o_{{ kubernetes.version_short }}
  - name: Add CRI-O stable repository
    become: yes
    apt_repository:
      repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os }}/ /"
      state: present
      filename: devel_kubic_libcontainers_stable


  # Add kubernetes dependencies
  - name: Add Kubernetes apt repository key
    become: yes
    apt_key:
      url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes.version_short }}/deb/Release.key
      state: present
      keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

  - name: Add Kubernetes apt repository
    become: yes
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes.version_short }}/deb/ /"
      filename: kubernetes
      state: present


  # Update & Upgrade
  - name: Update and upgrade apt packages
    become: yes
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
