---
- block:
  # Add CRI-O dependencies:
  - name: Import CRI-O repository keys
    become: yes
    apt_key:
      url: "https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{ kubernetes.version_short }}/deb/Release.key"
      state: present
      keyring: /etc/apt/trusted.gpg.d/cri-o-apt-keyring.gpg

  - name: Add CRI-O version-specific repository
    become: yes
    apt_repository:
      repo: "deb [signed-by=/etc/apt/trusted.gpg.d/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{ kubernetes.version_short }}/deb/ /"
      state: present
      filename: cri-o.list

 # Add kubernetes dependencies
  - name: Add Kubernetes apt repository key
    become: yes
    apt_key:
      url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes.version_short }}/deb/Release.key
      state: present
      keyring: /etc/apt/keyrings/kubernetes-keyring.gpg

  - name: Add Kubernetes apt repository
    become: yes
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes.version_short }}/deb/ /"
      filename: kubernetes.list
      state: present

  # Helm dependencies
  - name: Add helm repository keys
    become: yes
    apt_key:
      url:  https://baltocdn.com/helm/signing.asc
      state: present
      keyring: /etc/apt/keyrings/helm.gpg
  
  - name: Add Kubernetes apt repository
    become: yes
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
      filename: kubernetes
      state: present

  # Update & Upgrade
  - name: Update and upgrade apt packages
    become: yes
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
