---
- block:
  - name: Install Kubernetes packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - kubelet
      - kubectl
      - kubeadm

  - name: Install jq package
    apt:
      name: jq
      state: present

  - name: Configure kubelet with local IP address
    lineinfile:
      path: /etc/default/kubelet
      line: "KUBELET_EXTRA_ARGS=--node-ip={{ local_ip }}"
      create: true

  - name: Restart kubelet
    systemd:
      name: kubelet
      state: restarted

