---
- block:
  - name: Install tools over apt
    apt:
      name: '{{ packages }}'
    vars:
      packages:
        - cri-o
        - cri-o-runc
        - apt-transport-https
        - ca-certificates
        - kubelet
        - kubectl
        - kubeadm
        - jq
  - name: Setup crio
    become: true
    shell: |
      cat >> /etc/default/crio << EOF
      {{ environment }}
      EOF && \
      systemctl daemon-reload && \
      systemctl enable crio --now
  - name: Set local IP
    shell: |
      cat > /etc/default/kubelet << EOF && \
      KUBELET_EXTRA_ARGS=--node-ip={{ local_ip }}
      {{ environment }}
      EOF