---
- block:
  - name: Disable swap
    become: yes
    command: swapoff -a

  - name: Add swapoff to crontab
    become: yes
    cron:
      name: "Disable swap during reboot"
      user: root
      special_time: reboot
      job: "/sbin/swapoff -a"
