- name: Setup environment
  hosts: all
  remote_user: root
  become:      yes
  roles:
    - dns
    - disable-swap
    - bootup-modules
    - apt-setup
    # - tools
    - from-chatgpt
    - control-plane
